metric: auc_test_avg
direction: maximize
num_trials: 30
sampler:
  model:
    init_args:
      weight_kg:
        suggest_categorical:
          name: weight_kg
          choices: [0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0]
  optim:
    optimizer:
      init_args:
        lr:
          suggest_categorical:
            name: lr
            choices: [0.001, 0.003, 0.01, 0.03, 0.1]
    weight_decay:
      suggest_categorical:
        name: weihgt_decay
        choices:
          [
            0.01,
            0.03,
            0.1,
            0.3,
            1.0,
            2.0,
            3.0,
            4.0,
            5.0,
            6.0,
            7.0,
            8.0,
            9.0,
            10.0,
          ]
