model:
  class_path: src.models.RippleNet
  init_args:
    dataset: lastfm
    data_dir: data/processed/lastfm/seed_*
    max_hop: 3
    num_neighbors: 32
    embed_dim: 16
    weight_kg: 0.0
    batch_size_train: 4096
    num_workers: 32
optim:
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 0.01
  weight_decay: 6.0
trainer:
  logger:
    class_path: pytorch_lightning.loggers.MLFlowLogger
    init_args:
      experiment_name: lastfm_ripple_net
      tracking_uri: file:mlruns
  gpus:
    - 0
  check_val_every_n_epoch: 1
  max_epochs: 1000
  num_sanity_val_steps: -1
early_stopping:
  monitor: auc_val
  patience: 20
  mode: max
checkpoint:
  save_top_k: 1
num_runs: 5
