data_module:
  class_path: src.data.CTRPredictionDataModule
  init_args:
    dataset: lastfm
    data_dir: data/processed/lastfm/seed_0
    mode: kgcn
    max_hop: 1
    num_neighbors: 8
    reverse_triplet: true
    batch_size_train: 128
    num_workers: 8
model:
  class_path: src.models.KGCN
  init_args:
    embed_dim: 16
optim:
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 0.0001
trainer:
  gpus:
  - 1
  check_val_every_n_epoch: 1
  max_epochs: 10
  num_sanity_val_steps: -1
seed: 0
verbose: 1
