model:
  class_path: src.models.SimpleHGN
  init_args:
    dataset: lastfm
    data_dir: data/processed/lastfm/seed_0
    embed_dim: 16
    num_layers: 1
    hidden_dims_node: [16]
    hidden_dims_edge: 16
    num_heads: 1
    activation: elu
    dropout: 0.1
    use_edges_user: False
    batch_size_train: 128
    num_workers: 16
optim:
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 0.0001
trainer:
  logger:
    class_path: pytorch_lightning.loggers.MLFlowLogger
    init_args:
      experiment_name: lastfm_simple_hgn
      tracking_uri: file:mlruns
  gpus:
    - 0
  check_val_every_n_epoch: 1
  max_epochs: 100
  num_sanity_val_steps: -1
early_stopping:
  monitor: auc_val
  patience: 20
  mode: max
checkpoint:
  save_top_k: 3
verbose: 1
seed: 0
