model:
  class_path: src.models.SimpleHGN
  init_args:
    dataset: lastfm
    data_dir: data/processed/lastfm/seed_*
    embed_dim: 16
    num_layers: 1
    hidden_dims_node: 16
    hidden_dims_edge: 16
    num_heads: 1
    bias: true
    activation: elu
    dropout: 0.0
    dropout_attn: 0.0
    residual: true
    use_edges_user: True
    batch_size_train: 4096
    num_workers: 32
optim:
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 0.03
  weight_decay: 0.0
trainer:
  logger:
    class_path: pytorch_lightning.loggers.MLFlowLogger
    init_args:
      experiment_name: lastfm_simple_hgn_sns
      tracking_uri: file:mlruns
  gpus:
    - 0
  check_val_every_n_epoch: 1
  max_epochs: 1000
  num_sanity_val_steps: -1
early_stopping:
  monitor: auc_val
  patience: 20
  mode: max
checkpoint:
  save_top_k: 1
num_runs: 5
