model:
  class_path: src.models.RippleNet
  init_args:
    dataset: lastfm
    data_dir: data/processed/lastfm/seed_0
    max_hop: 3
    num_neighbors: 32
    embed_dim: 16
    batch_size_train: 256
    num_workers: 8
    weight_loss_kg: 0.02
optim:
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 0.005
      weight_decay: 1e-5
trainer:
  logger:
    class_path: pytorch_lightning.loggers.MLFlowLogger
    init_args:
      experiment_name: 'lastfm_ripple_net'
      tracking_uri: file:mlruns
  gpus:
  - 1
  check_val_every_n_epoch: 1
  max_epochs: 50
  num_sanity_val_steps: -1
early_stopping:
  monitor: auc_val
  patience: 20
  mode: max
checkpoint:
  save_top_k: 3
seed: 0
verbose: 1
