model:
  class_path: src.models.KGCN
  init_args:
    dataset: lastfm
    data_dir: data/processed/yelp/core_10_seed_*
    num_neighbors: 16
    embed_dim: 32
    num_layers: 2
    aggregation: cat
    weight_ls: 0.0
    dropout: 0.0
    dropout_attn: 0.0
    batch_size_train: 4096
    num_workers: 32
optim:
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 0.003
  weight_decay: 0.0
trainer:
  logger:
    class_path: pytorch_lightning.loggers.MLFlowLogger
    init_args:
      experiment_name: yelp_kgcn
      tracking_uri: file:mlruns
  gpus:
    - 0
  check_val_every_n_epoch: 1
  max_epochs: 1000
  num_sanity_val_steps: -1
early_stopping:
  monitor: auc_val
  patience: 20
  mode: max
checkpoint:
  save_top_k: 1
num_runs: 5
